package com.hospital.inventory.common.exception;

public enum ErrorCode {
	VALIDATION_ERROR,
	RESOURCE_NOT_FOUND,
	DUPLICATE_RESOURCE,
	BUSINESS_RULE_VIOLATION,
	UNAUTHORIZED,
	FORBIDDEN,
	INTERNAL_SERVER_ERROR
}
